--- #YAML:1.0
name:               Net-PayPal
version:            0.02
abstract:           Perl extension for PayPal's REST API server
author:
    - Sherzod B. Ruzmetov <sherzodr@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Cache::FileCache:  ~
    Crypt::Blowfish:   ~
    Crypt::CBC:        ~
    Crypt::SSLeay:     ~
    JSON:              ~
    LWP::UserAgent:    ~
    Test::More:        ~
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
